require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DirectDepositsController do

  # This should return the minimal set of attributes required to create a valid
  # DirectDeposit. As you add validations to DirectDeposit, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DirectDepositsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all direct_deposits as @direct_deposits" do
      direct_deposit = DirectDeposit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:direct_deposits).should eq([direct_deposit])
    end
  end

  describe "GET show" do
    it "assigns the requested direct_deposit as @direct_deposit" do
      direct_deposit = DirectDeposit.create! valid_attributes
      get :show, {:id => direct_deposit.to_param}, valid_session
      assigns(:direct_deposit).should eq(direct_deposit)
    end
  end

  describe "GET new" do
    it "assigns a new direct_deposit as @direct_deposit" do
      get :new, {}, valid_session
      assigns(:direct_deposit).should be_a_new(DirectDeposit)
    end
  end

  describe "GET edit" do
    it "assigns the requested direct_deposit as @direct_deposit" do
      direct_deposit = DirectDeposit.create! valid_attributes
      get :edit, {:id => direct_deposit.to_param}, valid_session
      assigns(:direct_deposit).should eq(direct_deposit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DirectDeposit" do
        expect {
          post :create, {:direct_deposit => valid_attributes}, valid_session
        }.to change(DirectDeposit, :count).by(1)
      end

      it "assigns a newly created direct_deposit as @direct_deposit" do
        post :create, {:direct_deposit => valid_attributes}, valid_session
        assigns(:direct_deposit).should be_a(DirectDeposit)
        assigns(:direct_deposit).should be_persisted
      end

      it "redirects to the created direct_deposit" do
        post :create, {:direct_deposit => valid_attributes}, valid_session
        response.should redirect_to(DirectDeposit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved direct_deposit as @direct_deposit" do
        # Trigger the behavior that occurs when invalid params are submitted
        DirectDeposit.any_instance.stub(:save).and_return(false)
        post :create, {:direct_deposit => {}}, valid_session
        assigns(:direct_deposit).should be_a_new(DirectDeposit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DirectDeposit.any_instance.stub(:save).and_return(false)
        post :create, {:direct_deposit => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested direct_deposit" do
        direct_deposit = DirectDeposit.create! valid_attributes
        # Assuming there are no other direct_deposits in the database, this
        # specifies that the DirectDeposit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DirectDeposit.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => direct_deposit.to_param, :direct_deposit => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested direct_deposit as @direct_deposit" do
        direct_deposit = DirectDeposit.create! valid_attributes
        put :update, {:id => direct_deposit.to_param, :direct_deposit => valid_attributes}, valid_session
        assigns(:direct_deposit).should eq(direct_deposit)
      end

      it "redirects to the direct_deposit" do
        direct_deposit = DirectDeposit.create! valid_attributes
        put :update, {:id => direct_deposit.to_param, :direct_deposit => valid_attributes}, valid_session
        response.should redirect_to(direct_deposit)
      end
    end

    describe "with invalid params" do
      it "assigns the direct_deposit as @direct_deposit" do
        direct_deposit = DirectDeposit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DirectDeposit.any_instance.stub(:save).and_return(false)
        put :update, {:id => direct_deposit.to_param, :direct_deposit => {}}, valid_session
        assigns(:direct_deposit).should eq(direct_deposit)
      end

      it "re-renders the 'edit' template" do
        direct_deposit = DirectDeposit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DirectDeposit.any_instance.stub(:save).and_return(false)
        put :update, {:id => direct_deposit.to_param, :direct_deposit => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested direct_deposit" do
      direct_deposit = DirectDeposit.create! valid_attributes
      expect {
        delete :destroy, {:id => direct_deposit.to_param}, valid_session
      }.to change(DirectDeposit, :count).by(-1)
    end

    it "redirects to the direct_deposits list" do
      direct_deposit = DirectDeposit.create! valid_attributes
      delete :destroy, {:id => direct_deposit.to_param}, valid_session
      response.should redirect_to(direct_deposits_url)
    end
  end

end
